from addratios import add_ratios
from carcombo import CarsWidget, selected_car
from dictionary import ClearEverything, clear_ratios, clear_stats
import geardropdown
from onexit import save_df
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from startapp import start
from statswidget import StatsWidget
from process import process_packet

__name__ = "pSilos_Nitto_Challenge_Stats_Tracker"

# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

start()
# Call the setupUi method to set up the widgets and layout


class mainwindow(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(mainwindow)

    def setupUi(self, mainwindow):
        QMainWindow.setObjectName("MainWindow")
        QMainWindow.setWindowModality(QtCore.Qt.WindowModal)
        QMainWindow.resize(793, 479)
        QMainWindow.setMaximumSize(QtCore.QSize(793, 479))
        QMainWindow.setAutoFillBackground(False)
        self.mainmenu = QtWidgets.QWidget(mainwindow)
        self.mainmenu.setObjectName("mainmenu")
        self.gear_ratio_combo = geardropdown.GearsWidget(parent=self)
        self.layout.addWidget(self.gear_ratio_combo)
        self.layout = QtWidgets.QVBoxLayout(self.mainmenu)
        self.layout.setObjectName("layout")
        self.add_ratios_button = add_ratios(selected_car, GearsWidget=gear_ratio_set, final_entry=gear_ratio_set,
                                            expected_et_entry=gear_ratio_set)

        # create ClearEverything widget
        clear_everything = ClearEverything(self)
        # add ClearEverything widget to layout
        self.layout().addWidget(clear_everything)

        self.layout().addWidget(self.add_ratios_button)
        self.clear_stats_button = clear_stats()
        self.layout().addWidget(self.clear_stats_button)
        self.clear_ratios_button = clear_ratios()
        self.layout().addWidget(self.clear_ratios_button)
        QMainWindow.setCentralWidget(self.mainmenu)

        # Create an instance of CarsWidget and add it to the central widget
        self.cars_widget = CarsWidget(self)
        self.setCentralWidget(self.cars_widget)

        # Create a layout and add it to the central widget
        self.central_layout = QtWidgets.QVBoxLayout()
        self.central_layout.addWidget(self.cars_widget)
        self.central_widget.setLayout(self.central_layout)

        self.pushButton = QtWidgets.QPushButton(self.mainmenu)
        self.pushButton.setGeometry(QtCore.QRect(550, 400, 101, 23))
        self.pushButton.setObjectName("pushButton")

        self.label = QtWidgets.QLabel(self.mainmenu)
        self.label.setGeometry(QtCore.QRect(560, 380, 81, 20))
        self.label.setObjectName("label")

        self.stats_widget = StatsWidget(self.mainmenu)
        self.layout.addWidget(self.stats_widget)
        self.carcombo = CarsWidget(self.mainmenu)
        self.layout.addWidget(self.carcombo)
        gears_ratio_combo = geardropdown.GearsWidget(self)
        self.layout.addWidget(self.gear_ratios_combo)

        self.app_name_label = QtWidgets.QLabel(self.mainmenu)
        self.app_name_label.setGeometry(QtCore.QRect(240, 290, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(40)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.app_name_label.setFont(font)
        self.app_name_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.app_name_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.app_name_label.setLineWidth(18)
        self.app_name_label.setMidLineWidth(36)
        self.app_name_label.setObjectName("app_name_label")
        self.app_name_label.setText("pSilo Nitto Challenge Stats Tracker")
        QMainWindow.setCentralWidget(self.mainmenu)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateui(self, topwindow):
        _translate = QtCore.QCoreApplication.translate
        topwindow.setWindowTitle(_translate("mainwindow", "mainwindow"))
        self.add_ratios_button.setText(_translate("mainwindow", "add ratios"))
        self.clear_stats_button.setText(_translate("mainwindow", "clear stats"))
        self.clear_ratios_button.setText(_translate("mainwindow", "clear ratios"))
        self.gear_1_label.setText(_translate("mainwindow", "Gear 1"))
        self.gear_2_label.setText(_translate("mainwindow", "Gear 2"))
        self.gear_3_label.setText(_translate("mainwindow", "Gear 3"))
        self.gear_4_label.setText(_translate("mainwindow", "Gear 4"))
        self.gear_5_label.setText(_translate("mainwindow", "Gear 5"))
        self.gear_6_label.setText(_translate("mainwindow", "Gear 6"))
        self.expected_et_label.setText(_translate("mainwindow", "Expected_et"))
        self.races_ran_label.setText(_translate("mainwindow", "Races Ran"))
        self.et_diff_label.setText(_translate("mainwindow", "ET Diff"))
        self.rt_diff_label.setText(_translate("mainwindow", "RT Diff"))
        self.mph_label.setText(_translate("mainwindow", "AVG MPH"))
        self.avg_et_label.setText(_translate("mainwindow", "AVG ET"))
        self.avg_rt_label.setText(_translate("mainwindow", "AVG RT"))
        self.settings__button.setText(_translate("mainwindow", "Settings"))
        self.pushButton.setText(_translate("mainwindow", "PushButton"))
        self.label.setText(_translate("mainwindow", "Func Coming"))
        self.foul_label.setText(_translate("mainwindow", "Fouls"))
        self.app_name_label.setText(_translate("mainwindow", "pSilo\'s Nitto Challenge Stats Tracker"))
        self.final_label.setText(_translate("mainwindow", "Final Gear"))
        self.expected_et_label.setText(_translate("mainwindow", "how fast bud"))
        self.races_ran_label_2.setText(_translate("mainwindow", "Total Races Ran"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.Qmainwindow()
    ui = mainwindow()
    ui.setupUi(QMainWindow)
    mainwindow.show()
    process_packet(gear_ratio_set)
    save_df()
    sys.exit(app.exec_())
