from addratios import add_ratios
from carcombo import CarsWidget, selected_car
from dictionary import ClearEverything, clear_ratios, clear_stats
import geardropdownframe as geardropdown, gear_ratio_set
from startapp import start
from statswidget import StatsWidget
from process import process_packet
from tkinter import tk

__name__ = "pSilos_Nitto_Challenge_Stats_Tracker"

# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

start()
# Call the setupUi method to set up the widgets and layout





root = tk.tk()

class MainWindow(tk.Toplevel):
    def __init__(self, master=None):
        tk.Toplevel.__init__(self, master)
        self.grabset()
        self.quitButton = tk.Button(self, text='Quit',
            command=self.quit)
        self.quitButton.pack()
        self.gear_ratio_combo = geardropdown.GearsWidget(parent=self)
        self.gear_ratio_combo.pack()
        self.add_ratios_button = add_ratios(selected_car, GearsWidget=gear_ratio_set,
                                            final_entry=gear_ratio_set, expected_et_entry= gear_ratio_set)

        # create ClearEverything widget
        clear_everything = ClearEverything(self)
        # add ClearEverything widget to layout
        self.layout().addWidget(clear_everything)

        self.layout().addWidget(self.add_ratios_button)
        self.clear_stats_button = clear_stats()
        self.layout().addWidget(self.clear_stats_button)
        self.clear_ratios_button = clear_ratios()
        self.layout().addWidget(self.clear_ratios_button)

        # Create an instance of CarsWidget and add it to the central widget
        self.cars_widget = CarsWidget(self)

        self.stats_widget = StatsWidget(self.mainmenu)
        self.layout.addWidget(self.stats_widget)
        self.carcombo = CarsWidget(self.mainmenu)
        self.layout.addWidget(self.carcombo)
        gears_ratio_combo = geardropdown.GearsWidget(self)
        self.layout.addWidget(self.gear_ratios_combo)

if __name__ == "__main__":
    import sys
    root.mainloop()
    root.withdraw()
    modal_window = MainWindow(root)
    process_packet(gear_ratio_set)