# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsmenu(object):
    def setupUi(self, settingsmenu):
        settingsmenu.setObjectName("settingsmenu")
        settingsmenu.resize(532, 548)
        self.centralwidget = QtWidgets.QWidget(settingsmenu)
        self.centralwidget.setObjectName("centralwidget")
        self.fonts = QtWidgets.QTabWidget(self.centralwidget)
        self.fonts.setGeometry(QtCore.QRect(0, 0, 131, 511))
        self.fonts.setObjectName("fonts")
        self.font_tab = QtWidgets.QWidget()
        self.font_tab.setObjectName("font_tab")
        self.fonts.addTab(self.font_tab, "")
        self.font_color_tab = QtWidgets.QWidget()
        self.font_color_tab.setObjectName("font_color_tab")
        self.fonts.addTab(self.font_color_tab, "")
        self.text_entry_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.text_entry_tabs.setGeometry(QtCore.QRect(130, 0, 181, 521))
        self.text_entry_tabs.setAcceptDrops(False)
        self.text_entry_tabs.setObjectName("text_entry_tabs")
        self.text_color_tab = QtWidgets.QWidget()
        self.text_color_tab.setObjectName("text_color_tab")
        self.text_entry_tabs.addTab(self.text_color_tab, "")
        self.entry_bg_color_tab = QtWidgets.QWidget()
        self.entry_bg_color_tab.setObjectName("entry_bg_color_tab")
        self.text_entry_tabs.addTab(self.entry_bg_color_tab, "")
        self.bg_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.bg_tab.setGeometry(QtCore.QRect(310, 0, 151, 511))
        self.bg_tab.setObjectName("bg_tab")
        self.bg_color_tab = QtWidgets.QWidget()
        self.bg_color_tab.setObjectName("bg_color_tab")
        self.bg_tab.addTab(self.bg_color_tab, "")
        self.add_custom_image = QtWidgets.QWidget()
        self.add_custom_image.setObjectName("add_custom_image")
        self.bg_tab.addTab(self.add_custom_image, "")
        settingsmenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settingsmenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        settingsmenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settingsmenu)
        self.statusbar.setObjectName("statusbar")
        settingsmenu.setStatusBar(self.statusbar)

        self.retranslateUi(settingsmenu)
        self.fonts.setCurrentIndex(0)
        self.text_entry_tabs.setCurrentIndex(1)
        self.bg_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(settingsmenu)

    def retranslateUi(self, settingsmenu):
        _translate = QtCore.QCoreApplication.translate
        settingsmenu.setWindowTitle(_translate("settingsmenu", "MainWindow"))
        self.fonts.setTabText(self.fonts.indexOf(self.font_tab), _translate("settingsmenu", "Fonts"))
        self.fonts.setTabText(self.fonts.indexOf(self.font_color_tab), _translate("settingsmenu", "Font Colors"))
        self.text_entry_tabs.setTabText(self.text_entry_tabs.indexOf(self.text_color_tab), _translate("settingsmenu", "Text Colors"))
        self.text_entry_tabs.setTabText(self.text_entry_tabs.indexOf(self.entry_bg_color_tab), _translate("settingsmenu", "Text BG Colors"))
        self.bg_tab.setTabText(self.bg_tab.indexOf(self.bg_color_tab), _translate("settingsmenu", "BG Colors"))
        self.bg_tab.setTabText(self.bg_tab.indexOf(self.add_custom_image), _translate("settingsmenu", "AddImage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsmenu = QtWidgets.QMainWindow()
    ui = Ui_settingsmenu()
    ui.setupUi(settingsmenu)
    settingsmenu.show()
    sys.exit(app.exec_())
